/*
 jBilling - The Enterprise Open Source Billing System
 Copyright (C) 2003-2011 Enterprise jBilling Software Ltd. and Emiliano Conde

 This file is part of jbilling.

 jbilling is free software: you can redistribute it and/or modify
 it under the terms of the GNU Affero General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 jbilling is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU Affero General Public License for more details.

 You should have received a copy of the GNU Affero General Public License
 along with jbilling.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.sapienter.jbilling.server.provisioning.task.mmsc;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.1
 * Thu May 28 10:10:49 EST 2009
 * Generated source version: 2.2.1
 * 
 */

@WebFault(name = "Exception", targetNamespace = "http://mmschandlerfacade.efs.teliasonera.se/")
public class MMSCException_Exception extends Exception {
    public static final long serialVersionUID = 20090528101049L;
    
    private com.sapienter.jbilling.server.provisioning.task.mmsc.MMSCException exception;

    public MMSCException_Exception() {
        super();
    }
    
    public MMSCException_Exception(String message) {
        super(message);
    }
    
    public MMSCException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public MMSCException_Exception(String message, com.sapienter.jbilling.server.provisioning.task.mmsc.MMSCException exception) {
        super(message);
        this.exception = exception;
    }

    public MMSCException_Exception(String message, com.sapienter.jbilling.server.provisioning.task.mmsc.MMSCException exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public com.sapienter.jbilling.server.provisioning.task.mmsc.MMSCException getFaultInfo() {
        return this.exception;
    }
}
